name = "TimeEvoMPS"
uuid = "1bec0e0a-d6ff-11e9-2fd9-7928ca571592"
authors = ["orialb <orialb1@gmail.com>"]
version = "0.1.0"

[deps]
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
